spring.application.name=cinegraph-backend

# TMDB
tmdb.access-token=${TMDB_ACCESS_TOKEN}

# MySQL
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/cinegraph}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=${PORT:8080}